import Head from "next/head";
import DashboardLayout from "../layouts/Dashboard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout headerName="About">
        {/* Replace with your content */}
        About
        <div className="px-4 py-4 sm:px-0">
          <div className="h-96 rounded-lg border-4 border-dashed border-gray-200" />
        </div>
        {/* /End replace */}
      </DashboardLayout>
    </>
  );
}
